# Generated by Django 5.0.4 on 2024-06-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_servicerequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Тема заявки'),
        ),
    ]
