# Generated by Django 5.0.4 on 2024-06-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_servicerequest_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True, verbose_name='Номер телефона'),
        ),
    ]
