# Generated by Django 5.0.4 on 2024-06-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_servicerequest_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='phone_number',
        ),
    ]
